name: Build
on: 
  push:
    branches:
     - dev
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo Hello, world!

      - name: testing the integration 
        uses: bodlasai/github-actions/.github/workflows/simple.yml@master
