name: HelloWorld 
on:
  workflow_dispatch:
jobs:
  build:
   runs-on: ubuntu-latest
   steps:
    - name: Checkout using the Template File 
      uses: actions/checkout@v2 
  checkout:
    uses: bodlasai/github-actions/.github/workflows/simple.yml@master
  
  
  
