name: Build
on: 
  push:
    branches:
     - dev
jobs:
  call-workflow-passing-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script
        run: echo Hello, world!

      - name: testing the integration 
        uses: bodlasai/github-actions/.github/workflows/simple.yml@master
