name: Build
on: 
  push:
    branches:
     - dev
jobs:
  build:
    name: Build
    runs-on: ubutu-latest
    steps:
      - name: echo the sting
        run: echo "hello git actions"
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: test1
        uses: bodlasai/github-actions@master
     
