name: s3_inputs_trigger

on:
  workflow_dispatch:

jobs:
  call-workflow-passing-data:
    uses: bodlasai/github-actions/.github/workflows/test_in.yml@main
    with:
      username: saibucket0100/testing2
    secrets: inherit
# jobs:
#   builds:
#     uses: bodlasai/github-actions/.github/workflows/test_s3.yml@main
#      with:
#       username: saibucket0100/testing2
#      #foldername: test1234

    #uses: bodlasai/github-actions/.github/workflows/test_s3.yml@main
   
