name: Call a reusable workflow

on:
  workflow_dispatch:

jobs:
  builds:
    uses: bodlasai/github-actions/.github/workflows/test_s3.yml@main
#     with:
#      username: saibucket0100
#      foldername: test1234
