name: Call a reusable workflow

on:
  workflow_dispatch:

jobs:
  builds:
    uses: bodlasai/github-actions/.github/workflows/test_s3.yml@main
    with:
     bucketname: sai123
#      foldername: test1234
