name: Call a reusable workflow

on:
  schedule:
     - cron: "*/2 * * * *"
  workflow_dispatch:

jobs:
  builds:
    uses: bodlasai/github-actions/.github/workflows/sample1.yml@master
    with:
     bucketname: saibucket0100
#      foldername: test1234
